# Generated by Django 2.0.6 on 2018-06-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetalFighter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': '测试用户', 'verbose_name_plural': '测试用户'},
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='sigdate',
        ),
    ]
