# Generated by Django 2.0.6 on 2018-06-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetalFighter', '0002_auto_20180625_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk1', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={},
        ),
    ]
