# Generated by Django 2.0.6 on 2018-06-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetalFighter', '0004_auto_20180625_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('subscribe', models.CharField(blank=True, max_length=60, verbose_name='描述')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('pic_no', models.IntegerField(default=1, verbose_name='图片编号')),
                ('context', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=15, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('status', models.BooleanField(verbose_name='账户状态')),
                ('info', models.TextField(verbose_name='个人说明')),
                ('user_name', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('role', models.BooleanField(verbose_name='VIP状态')),
                ('balance', models.BigIntegerField(verbose_name='账户余额')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=0, verbose_name='测试数'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='测试邮箱'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='测试名'),
        ),
    ]
