# Generated by Django 2.0.6 on 2018-06-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetalFighter', '0005_auto_20180627_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, verbose_name='昵称'),
        ),
    ]
