# Generated by Django 3.0.5 on 2020-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('userEmail', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('voteId', models.CharField(max_length=10)),
                ('voteKey', models.CharField(blank=True, max_length=30)),
                ('resDate', models.DateField(auto_now_add=True)),
                ('voteRes', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='voteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starterId', models.CharField(max_length=10)),
                ('starterEmail', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField()),
                ('voteKey', models.CharField(blank=True, max_length=30)),
                ('contentJson', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(default='NewUser', max_length=30),
        ),
    ]
