# Generated by Django 3.0.5 on 2020-04-27 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0002_auto_20200426_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
