# Generated by Django 3.0.5 on 2020-04-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0003_auto_20200427_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteprofile',
            name='starterEmail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='voteprofile',
            name='voteKey',
            field=models.CharField(blank=True, default='F3qhDucb', max_length=30),
        ),
    ]
