# Generated by Django 3.0.5 on 2020-05-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0004_auto_20200427_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='userEmail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='voteprofile',
            name='voteKey',
            field=models.CharField(blank=True, default='1oiBbevd', max_length=30),
        ),
    ]
