# Generated by Django 3.0.5 on 2020-05-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0008_auto_20200511_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteprofile',
            name='voteKey',
            field=models.CharField(blank=True, default='C7vlrVes', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('userEmail', 'voteId')},
        ),
    ]
