# Generated by Django 3.0.5 on 2020-05-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0009_auto_20200511_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteprofile',
            name='voteKey',
            field=models.CharField(blank=True, default='IXRBQUPZ', max_length=30, unique=True),
        ),
    ]
