# Generated by Django 3.0.5 on 2020-05-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteBack', '0012_auto_20200511_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteprofile',
            name='voteKey',
            field=models.CharField(blank=True, default='Of6aIvrL', max_length=30),
        ),
    ]
